name: kargo_app
description: A new Flutter project.

publish_to: "none"

version: 2.1.5+20

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconly:
  pull_to_refresh: ^2.0.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  persistent_bottom_nav_bar: ^5.0.2
  flutter_svg: ^1.1.5
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  badges: ^3.1.1
  dotted_line: ^3.2.2
  flutter_dash: ^1.0.0
  zoom_widget: ^2.0.1
  dio: ^5.3.1
  intl: 
  lottie: ^2.3.2
  easy_localization: ^3.0.3
  url_launcher: ^6.2.4
  package_info_plus: ^4.2.0
  get:
  flutter_spinkit: ^5.2.0
  flutter_local_notifications: ^15.1.0+1
  flutter_phone_direct_caller: ^2.1.1
  photo_view: ^0.14.0
  flutter_swipe_detector: ^2.0.0
  cached_network_image: ^3.3.1
  upgrader: 
  firebase_remote_config: ^4.3.17


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/languages/

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin_Condensed-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Onest-VariableFont_wght.ttf
